import {NgModule} from '@angular/core';
import {
    NzBreadCrumbModule,
    NzButtonModule,
    NzCardModule,
    NzCheckboxModule,
    NzDatePickerModule,
    NzDescriptionsModule,
    NzDividerModule,
    NzDropDownModule, NzEmptyModule,
    NzFormModule,
    NzGridModule,
    NzIconModule,
    NzInputModule,
    NzInputNumberModule,
    NzLayoutModule,
    NzMenuModule,
    NzMessageModule,
    NzModalModule,
    NzPageHeaderModule,
    NzPopconfirmModule,
    NzRadioModule, NzResultModule,
    NzSelectModule,
    NzTableModule,
    NzTabsModule,
    NzToolTipModule,
    NzTypographyModule
} from 'ng-zorro-antd';
import {NzSpaceModule} from 'ng-zorro-antd/space';


@NgModule({
    declarations: [],
    imports: [
        NzFormModule,
        NzInputModule,
        NzButtonModule,
        NzCheckboxModule,
        NzIconModule,
        NzLayoutModule,
        NzBreadCrumbModule,
        NzMenuModule,
        NzToolTipModule,
        NzPageHeaderModule,
        NzTableModule,
        NzDividerModule,
        NzTabsModule,
        NzDatePickerModule,
        NzDropDownModule,
        NzTypographyModule,
        NzSelectModule,
        NzSpaceModule,
        NzCardModule,
        NzMessageModule,
        NzModalModule,
        NzDescriptionsModule,
        NzPopconfirmModule,
        NzInputNumberModule,
        NzRadioModule,
        NzGridModule,
        NzCardModule,
        NzButtonModule,
        NzEmptyModule,
        NzResultModule,
    ],
    exports: [
        NzFormModule,
        NzInputModule,
        NzButtonModule,
        NzCheckboxModule,
        NzIconModule,
        NzLayoutModule,
        NzBreadCrumbModule,
        NzMenuModule,
        NzToolTipModule,
        NzPageHeaderModule,
        NzTableModule,
        NzDividerModule,
        NzTabsModule,
        NzDatePickerModule,
        NzDropDownModule,
        NzTypographyModule,
        NzSelectModule,
        NzSpaceModule,
        NzCardModule,
        NzMessageModule,
        NzModalModule,
        NzDescriptionsModule,
        NzPopconfirmModule,
        NzInputNumberModule,
        NzRadioModule,
        NzGridModule,
        NzCardModule,
        NzButtonModule,
        NzEmptyModule,
        NzResultModule,
    ]
})
export class MyNgZorroModule {
}
